#!/usr/bin/env python3
"""Export numerical supplementary tables from completed reports; no model fitting."""
from pathlib import Path
import csv,json
ROOT=Path(__file__).resolve().parents[2]
HERE=Path(__file__).resolve().parent
ANALYSIS=ROOT/'outputs/analysis'
TOPIC_LABELS=['TIMP1/COL3A1', 'JUNB/DNAJB1', 'COL1A1/COL1A2', 'IGFBP7/IGFBP5', 'TAGLN/ACTA2', 'KRT14/KRT10', 'CFD/APOD', 'DCN/CFD', 'DCD/SAT1', 'IGFBP7/SPARCL1', 'FOS/IGFBP7', 'HLA-DRA/CD74', 'IGFBP7/TAGLN', 'FOS/JUNB', 'DNAJB1/FOS']
def report(n):return json.loads((ANALYSIS/n/'report.json').read_text())
def esc(x):
 return str(x).replace('&',r'\&').replace('%',r'\%').replace('_',r'\_').replace('#',r'\#')
def historical(n):return json.loads((ROOT/'outputs'/n/'report.json').read_text())
def probability(x):return f'{float(x):.3g}' if x is not None else '—'
def f(x,n=4):return '—' if x in (None,'') else f'{float(x):.{n}f}'
def table(label,caption,headers,rows,widths):
 col='@{}'+''.join('p{'+str(w)+'mm}' for w in widths)+'@{}'
 header=' & '.join(r'\textbf{'+esc(h)+'}' for h in headers)+r' \\'
 # Longtable measures its caption/header and starts only when a row fits.
 # Keep the first and last row pairs together without reserving an estimated
 # table height, which can push otherwise usable content onto another page.
 body='\n'.join(' & '.join(esc(c) for c in row)+(r' \\*' if len(rows)>1 and i in (0,len(rows)-2) else r' \\') for i,row in enumerate(rows))
 return '\n'.join([r'{\small',r'\begin{longtable}{'+col+'}',r'\caption{'+caption+r'}\label{'+label+r'}\\',r'\toprule',header,r'\midrule\endfirsthead',r'\multicolumn{'+str(len(headers))+r'}{l}{\tablename\ \thetable\ (continued)}\\',r'\toprule',header,r'\midrule\endhead',r'\bottomrule\endfoot',body,r'\end{longtable}',r'}'])
def csvrows(n):return list(csv.DictReader((ROOT/'manuscripts/tables'/n).open()))
# Each exported table lives in TeX; no Markdown draft is used by the build.
p1=[]
p1.append(table('tab:p1patients','Author-mapped GSE165816 DFU patient scores (7 healed, 4 not healed). Each score is the mean frozen fibroblast-associated topic loading over all retained cells in the listed foot specimens; pooling cells weights repeated specimens by retained cell count. Cells are counts, not independent outcome observations. Patient identifiers are study-derived pseudonyms and G labels identify specimens. The outcome is the source-study category within 12 weeks, not an individual healing day. Scores are on the topic-loading scale from zero to one.', ['Patient','Outcome','Specimens','Cells','All-cell mean'],[[r['patient_id'].split('_')[-1],r['healing_status'].replace('_',' '),r['sample_titles'].replace('|',', '),r['n_cells'],f(r['score_cell_weighted'])] for r in csv.DictReader((ROOT/'outputs/cohort_metadata/gse165816_patient_unit_remap/patient_scores.csv').open())],[22,29,39,26,49]))
rows=csvrows('representation_inference.csv')
p1.append(table('tab:p1sampleauc',r'Exploratory discrimination across 9 healing and 5 non-healing GSE165816 specimens. AUC is the area under the ROC curve for leave-one-sample-out scores; higher values favour healing. The percentile 95\% intervals use 4,000 arm-stratified resamples of fixed out-of-fold scores. One-sided permutation probabilities and null means rerun fold-dependent orientation and fitting. PCA is principal component analysis; NMF is nonnegative matrix factorization. The frozen topic encoder itself used the discovery expression cohort. Repeated patients limit independence, and none of the six paired AUC-difference intervals excludes zero.',['Readout','AUC','Bootstrap 95% interval','Permutation p','Null mean'],[[r['readout'].replace('Fibroblast topic','Fibroblast topic'),f(r['auc'],3),f(r['ci_low'],3)+' to '+f(r['ci_high'],3),f(r['p_one_sided']),f(r['null_mean'],3)] for r in rows],[25,20,49,37,34]))
rows=csvrows('patient_unit_and_anatomy.csv')
p1.append(table('tab:p1patientauc','Patient-unit discrimination and anatomical sensitivity within GSE165816. The first four rows are leave-one-patient-out AUCs for 7 healing and 4 non-healing patients, with 4,000 arm-stratified bootstrap draws of fixed scores and one-sided label-permutation probabilities. PCA and NMF denote principal component analysis and nonnegative matrix factorization. The final row is the foot-minus-forearm all-cell fibroblast-associated topic mean difference in 10 paired patients, with a 4,000-draw paired bootstrap interval and a two-sided exhaustive sign-flip probability using add-one correction. Its Benjamini--Hochberg q value across 15 topics is 0.0402. The two row types have different estimands; neither supplies external validation.',['Readout','Estimate','Bootstrap 95% interval','Permutation p'],[[r['quantity'].replace('_',' ').replace('Fibroblast topic','Fibroblast topic'),f(r['estimate'],4),f(r['lower_95'],4)+' to '+f(r['upper_95'],4),f(r['p_value'],4)] for r in rows],[45,25,59,38]))
rows=csvrows('representation_cross_method.csv')
p1.append(r'\Needspace{155pt}'+'\n'+table('tab:p1correlations','Spearman correlations between the four representative sample-level prediction scores across the same 14 DFU specimens (9 healing, 5 non-healing). Fibroblast topic is the frozen all-cell loading, Module the specified fibro-inflammatory score, PCA principal component analysis and NMF nonnegative matrix factorization. Each row is one pair of readouts; values are descriptive point estimates without confidence intervals or multiplicity-adjusted tests. Related scores do not establish equivalent discrimination or rank methods.',['Readout A','Readout B','Spearman correlation'],[[r['readout_a'].replace('Fibroblast topic','Fibroblast topic'),r['readout_b'].replace('Fibroblast topic','Fibroblast topic'),f(r['spearman_rho'])] for r in rows],[53,53,65]))
d=report('design_power_simulation'); rows=[]
for key,block in [('design_a_detect_difference','Detect difference'),('design_b_declare_equivalence','Equivalence under zero difference')]:
 for k,v in d[key].items():rows.append([block,k.split('_')[-1],v['total'],f"{v['n_healed']} / {v['n_not_healed']}",f(v['power'],3)])
p1.append(table('tab:p1design','Conditional next-cohort simulations for all-cell fibroblast-associated topic mean loading. Rows assume one independent patient per observation, no missing outcomes, healing allocation near 9/14, and arm SDs 0.04845 and 0.01584 estimated from discovery specimens. Two-sided Welch tests assess candidate mean differences; Welch two-one-sided tests assess equivalence under a true difference of zero, at alpha=0.05. Total and arm columns give the simulated observation counts; power uses 4,000 draws per candidate size. Values near 0.80 have Monte Carlo error and are approximate search outputs. Candidate differences and margins are inputs, not clinical minimum important differences or validated recruitment targets.',['Design','Difference / margin','Total','Healing / other','Estimated power'],rows,[50,30,20,30,35]))
# Numerical semantic and inferential control summaries, directly read from existing CSVs.
s=report('mixture_semantic_inference')
rows=csvrows('mixture_semantic_inference.csv')
p1.append(table('tab:p1semantics',r'Association between mean fibroblast-associated topic loading within fibroblasts and the threshold-defined high-state fraction across 25 GSE165816 specimens. The Spearman row gives the observed correlation and percentile 95\% limits from 10,000 sample-row bootstrap draws. The leave-one-out row gives the minimum and maximum of 25 recalculations, not a confidence interval; a dash means no single point estimate applies. A separate 10,000-draw permutation analysis gave a two-sided add-one probability of 0.00010 and a central null interval from -0.4025 to 0.4072. Samples may share patients, and the two summaries share cells.',['Summary','Estimate','Lower endpoint','Upper endpoint'],[[r['metric'].replace('_',' '),f(r['estimate']),f(r['ci_low']),f(r['ci_high'])] for r in rows],[63,28,39,37]))
# The same depth definition is used in every plotted cohort; both are tabulated.
rows=[]
d=report('external_immune_axis')
for name,c in d['cohorts'].items():
 assoc=c['sample_level_associations']
 rows.append([name,c['sample_count'],*[f(assoc[k]['rho'],3) for k in ['immune_fraction_exclusive','b_plasma_share_of_immune','median_genes_per_cell','median_umis_per_cell']]])
c=report('external_gse268834_projection');assoc=c['sample_level_associations']
rows.append(['GSE268834',8,*[f(assoc[k]['rho'],3) for k in ['immune_fraction_exclusive','b_plasma_share_of_immune','median_genes_per_cell','median_umis_per_cell']]])
p1.append(table('tab:p1external','External sample-level Spearman correlations with the frozen fibroblast-associated topic mean under exclusive lineage gates. Immune fraction divides immune-assigned cells by all retained cells; B/plasma share divides B/plasma cells by immune-assigned cells. Detected genes and unique molecular identifiers (UMIs) are separate per-sample medians over QC cells. All entries are descriptive point estimates without confidence intervals. Specimens are not verified independent patients, and no listed cohort supplies a qualifying patient-level healing outcome.', ['Cohort','Samples','Immune fraction','B/plasma share','Detected genes','UMIs'],rows,[29,18,29,29,29,29]))

# Full exploratory covariate scan; preserve the historical rounded cut and sample unit.
d=historical('stratifier_sweep')
readable={'frac_b_plasma':'B/plasma fraction','frac_endothelial':'Endothelial fraction','frac_fibroblast':'Fibroblast fraction','frac_keratinocyte':'Keratinocyte fraction','frac_lymphatic_ec':'Lymphatic endothelial fraction','frac_mast':'Mast-cell fraction','frac_melanocyte':'Melanocyte fraction','frac_myeloid':'Myeloid fraction','frac_pericyte_smc':'Pericyte/smooth-muscle fraction','frac_sweat_gland':'Sweat-gland fraction','frac_t_cell':'T-cell fraction','tech_diss':'Fibroblast dissociation score','tech_umi':'Fibroblast median UMI count','tech_ptprc_pos':'Fibroblast PTPRC-positive fraction','meta_g_number':'Numeric G specimen label','n_cells_total':'Total retained cells','n_fibroblasts':'Retained fibroblasts'}
for i in range(1,15):readable[f'fib_mean_topic_{i}']=f'Fibroblast {TOPIC_LABELS[i]} mean'
rows=[[readable[r['covariate']],r['n'],f(r['rho']),probability(r['p']),probability(r['q_bh'])] for r in d['sweep']]
p1.append(table('tab:p1covariates',r'Complete exploratory covariate screen in 25 discovery specimens. Each row correlates the fibroblast high-state fraction, using the historical rule loading at least 0.184, with one of 31 covariates. Lineage fractions use all retained cells; technical summaries and topic means use fibroblasts. Values are Spearman rho, two-sided asymptotic p and Benjamini--Hochberg q across all 31 tests, ordered by absolute rho; 14 rows have q below 0.05. UMI means unique molecular identifier. The G label is an identifier, not an established batch or time variable. Repeated patients, shared cells and compositional constraints limit independence; these marginal associations are not causal or healing-validation tests.',['Covariate','Specimens','Spearman rho','Raw p','BH q'],rows,[76,20,25,22,22]))
d=historical('ambient_invariance')
rows=[]
for name,n,r2,b in [('Before immune-transcript exclusion',24,None,d['test_A_purity']['bimodal_all']),('After immune-transcript exclusion',24,None,d['test_A_purity']['bimodal_pure']),('Immune-covariate residuals',25,d['test_B_residual']['r2_immune_covariates'],d['test_B_residual']['bimodal_residual']),('Placebo-covariate residuals',25,d['test_B_placebo']['r2'],d['test_B_placebo']['bimodal_residual'])]:
 rows.append([name,n,f(r2),f(b['bic_1'],3),f(b['bic_2'],3),f(b['delta_bic'],3)])
p1.append(table('tab:p1ambient',r'Immune-transcript exclusion and residual-mixture controls. BIC denotes Bayesian information criterion, fitted to sample high-state fractions or their regression residuals; the difference is BIC for one Gaussian minus BIC for two. Positive differences favour two components. The first two rows share 24 matched specimens and have fraction correlation 0.9887. Residual regressions use all 25 specimens: immune covariates are B/plasma, T-cell and myeloid fractions plus immune-transcript positivity; placebos are pericyte/smooth-muscle, endothelial, melanocyte and sweat-gland fractions. R squared is variance explained by each regression and is inapplicable to unadjusted rows (dash). Both residual differences are negative, so the analysis does not establish immune-specific separation.',['Summary','n','R squared','BIC one','BIC two','Difference'],rows,[64,13,22,23,23,20]))
d=historical('celltype_resolved');rows=[]
for cohort,c in d['cohorts'].items():
 for key,name in [('composition_test','Fibroblast fraction'),('whole_sample_test','All-cell topic mean'),('within_lineage_test','Within-fibroblast topic mean')]:
  v=c[key];rows.append([cohort.split('_')[0],name,f(v['ratio'],3),f(v['ratio_ci95'][0],3)+' to '+f(v['ratio_ci95'][1],3),probability(v['p'])])
p1.append(table('tab:p1lineage',r'Historical sample-level lineage and loading contrasts. Ratios divide the healing-arm mean by the non-healing-arm mean; intervals are percentile 95\% limits from 20,000 within-arm sample bootstraps, and p values are two-sided Mann--Whitney tests. GSE165816 uses 9 versus 5 DFU specimens; GSE231643 uses 5 versus 3 title-labelled specimens. The discovery ratios come from the saved lineage-projection analysis and are distinct from the later deterministic all-cell patient contrast. Fibroblast fraction uses all cells as denominator; fibroblast mean uses only assigned fibroblasts. These are separate estimands. Repeated discovery patients and unavailable external patient mappings prevent independent outcome validation.',['Cohort','Readout','Mean ratio','Bootstrap 95% interval','Raw p'],rows,[29,49,24,42,21]))
readouts={'topic_simplex_theta0':'Fibroblast topic','module_score':'Module','pca':'PCA','nmf':'NMF'}
rows=[]
for name,unit in [('representation_inference','14 specimens'),('patient_unit_representation_benchmark','11 patients')]:
 for pair,v in report(name)['pairwise_auc_difference'].items():
  a,b=pair.split('__minus__');rows.append([unit,readouts[a]+' minus '+readouts[b],f(v['observed_difference']),f(v['bootstrap_95_ci'][0])+' to '+f(v['bootstrap_95_ci'][1])])
p1.append(table('tab:p1aucdifferences',r'All six paired AUC differences at each analysis unit. Each contrast subtracts the second leave-one-out readout from the first. Percentile 95\% intervals use 4,000 common-index, arm-stratified bootstrap draws of fixed out-of-fold scores: 9 versus 5 specimens or 7 versus 4 mapped patients. PCA and NMF denote principal component analysis and nonnegative matrix factorization. No sample-unit interval excludes zero; patient-unit Fibroblast topic minus NMF and Module minus NMF intervals do. The intervals are exploratory, are not adjusted across pairs, and do not refit the entire representation in each bootstrap draw.',['Unit','AUC contrast','Difference','Bootstrap 95% interval'],rows,[31,59,26,51]))
d=report('paired_anatomical_control');rows=[]
for v in d['all_topic_contrasts']:
 rows.append([TOPIC_LABELS[v['topic']],f(v['observed_difference_foot_minus_forearm']),f(v['bootstrap_95_ci'][0])+' to '+f(v['bootstrap_95_ci'][1]),probability(v['p_two_sided_exact_sign_flip']),probability(v['bh_q'])])
p1.append(table('tab:p1anatomy',r'Complete paired anatomical control across 15 topics in 10 author-mapped patients. Differences are mean all-cell loadings in foot minus forearm, after cell-count-weighted collapse of repeated foot specimens. Intervals are percentile 95\% limits from 4,000 paired-patient bootstrap draws. Two-sided p values enumerate all 1,024 sign allocations and retain add-one correction; q values use Benjamini--Hochberg across 15 topics. The TIMP1/COL3A1, COL1A1/COL1A2, CFD/APOD and IGFBP7/TAGLN loadings have q below 0.05. Labels list the two leading decoder genes; they do not assert cell-type identity. Bootstrap intervals and permutation tests need not be dual. This is an anatomical sensitivity control within the discovery source, not a healing endpoint.',['Leading genes','Foot minus forearm','Bootstrap 95% interval','Sign-flip p','BH q'],rows,[42,35,48,21,19]))
rows=[]
for unit,d in [('14 specimens',report('patient_mapping_equivalence')),('11 patients',historical('cohort_metadata/gse165816_patient_unit_remap'))]:
 for v in d['equivalence']['margins']:
  rows.append([unit,f(v['bound'],2),probability(v['p_lower']),probability(v['p_upper']),'Yes' if v['equivalent_at_alpha_0_05'] else 'No'])
p1.append(table('tab:p1equivalence',r'Complete Welch two-one-sided-test sensitivity grids for the all-cell mean fibroblast-associated topic contrast. The symmetric margin is on the loading scale, and both lower and upper one-sided p values must be below 0.05 for the final column to be Yes. Sample rows use 9 versus 5 specimens; patient rows use 7 versus 4 mapped patients with cell-count-weighted repeat collapse. Margins were examined retrospectively and have no externally justified clinical meaning. A Yes entry therefore records a mathematical sensitivity result, not demonstrated clinical equivalence.',['Unit','Margin','Lower-test p','Upper-test p','Both below 0.05'],rows,[33,23,33,33,43]))
d=historical('method_constant_sensitivity');rows=[]
for v in d['cut_sweep']['rows']:
 rows.append([f(v['cut']),f(v['A_rho_mean_vs_weight']),f(v['C_ratio'],3),probability(v['C_p']),'Healthy' if v['B_counterexample_holds'] else 'DFU'])
p1.append(table('tab:p1cuts',r'All 18 state-cut sensitivity evaluations for the frozen K=15 topic. Spearman rho correlates fibroblast mean loading with the threshold-defined high-state fraction across 25 specimens. The ratio compares mean high-state fractions in 9 healing versus 5 non-healing specimens; p is the unadjusted two-sided Mann--Whitney probability. The last column gives the group containing the largest fraction. The grid includes the fitted cut rounded to 0.1843. Four cuts have p below 0.05; these are dependent sensitivity analyses, not 18 independent confirmations.',['State cut','Semantic rho','Healing / non-healing','Raw p','Largest fraction'],rows,[27,31,43,25,39]))
rows=[]
for v in d['k_sweep']['rows']:
 rows.append([v['K'],'IGFBP-rich' if v['K']==10 else 'CHI3L1/COL3A1-rich',f(v['derived_cut']),f(v['A_rho_mean_vs_weight']),probability(v['C_p']),'Yes' if v['B_counterexample_holds'] else 'No'])
p1.append(table('tab:p1capacity',r'Topic-capacity sensitivity after tracking the TIMP1-carrying topic at each K. Gene-based descriptions identify the tracked loading; each fit supplies its own two-Gaussian midpoint cut. Semantic rho uses 25 specimens; the unadjusted healing-arm p value uses 9 versus 5 high-state-fraction summaries. The final column asks whether the maximum fraction occurs in healthy skin. At K=10 the tracked topic is a different IGFBP-rich programme and the counterexample fails. Topics across capacities are not assumed to have identical biological meaning.',['K','Programme description','Derived cut','Semantic rho','Healing p','Healthy maximum'],rows,[12,46,25,26,21,35]))
d=report('design_power_simulation');rows=[]
for key,v in d['design_c_resolve_auc_difference'].items():
 rows.append([key.split('_')[-1],v['total'],f"{v['n_healed']} / {v['n_not_healed']}",f(v['power'],3)])
p1.append(table('tab:p1aucdesign',r'Exploratory binormal planning simulation for paired AUC differences. Two candidate AUCs are centred on 0.80, separated by the stated gap, with within-class score-noise correlation 0.5022 and healing allocation near 9/14. Each searched total uses 4,000 simulation draws and a model-based normal approximation for the paired difference at alpha=0.05. Totals assume one observation per independent patient and no missing outcome. The gaps are hypothetical inputs; the approximate 80\% power search does not establish actual clinical performance, calibrated patient-test power or a validated recruitment target.',['Candidate AUC gap','Total observations','Healing / non-healing','Estimated power'],rows,[44,38,51,34]))

# Keep design simulations together and end with the full threshold grid.
p1.insert(5, p1.pop())
p1[-2], p1[-1] = p1[-1], p1[-2]

r=json.loads((ROOT/'outputs/robustness_extensions/report.json').read_text())['patient']
a=r['patient_semantics'];b=r['patient_outcome_influence']
rows=[['Mean versus high-state fraction','20 patients',f(a['rho']),f(a['bootstrap_95_interval'][0])+' to '+f(a['bootstrap_95_interval'][1]),f(a['omission_range'][0])+' to '+f(a['omission_range'][1])],['Healing minus non-healing','11 patients',f(b['observed_difference']),'Not recalculated',f(b['omission_range'][0])+' to '+f(b['omission_range'][1])]]
p1.insert(-2,table('tab:p1robustness',r'Patient-level robustness in the discovery cohort. The first row correlates fibroblast mean loading with the high-state fraction after weighting repeated specimen summaries by fibroblast count within 20 patients (25 specimens). Its percentile 95\% interval uses 10,000 patient resamples, seed 217. The second row uses the previously defined all-cell healing contrast in 7 healing and 4 non-healing patients; its original interval remains in the outcome table. Omission ranges give the minimum and maximum after deleting one patient at a time (20 or 11 omissions), not confidence limits. Neither analysis refits the expression model, changes the state cut, adds patients, or provides external validation.',['Quantity','Unit','Estimate','Patient bootstrap 95%','Patient-omission range'],rows,[43,24,21,39,39]))
d=json.loads((ROOT/'outputs/mathematical_audit/measurement/report.json').read_text())
m=d['state_decomposition'];ranges=m['ranges']
rows=[['Cell-pooled low-bin mean',f(m['low_reference'],5),'All 19,410 fibroblasts'],
      ['Cell-pooled high-bin mean',f(m['high_reference'],5),'All 19,410 fibroblasts'],
      ['Specimen low-bin means',' to '.join(f(v,5) for v in ranges['low_state_mean']),'25 nonempty low bins'],
      ['Specimen high-bin means',' to '.join(f(v,5) for v in ranges['high_state_mean']),'16 nonempty high bins'],
      ['Specimens with an empty bin',m['empty_bin_specimens'],'9 of 25; high bin empty'],
      ['Within-state residual range',' to '.join(f(v,5) for v in ranges['within_state_residual']),'All 25 specimens'],
      ['Within-state residual RMS',f(m['specimen_weighted_residual_rms'],5),'Equal specimen weights']]

p1.append(table('tab:p1math',r'Exact mean decomposition on the saved 19,410 discovery fibroblasts in 25 specimens. The cut is 0.184295848; empirical bin means are distinct from fitted Gaussian-component means. The constant-state approximation uses the cell-pooled low/high means, and its residual is the observed specimen mean minus that approximation. RMS denotes root-mean-square residual with equal specimen weights. Ranges exclude undefined means for empty bins; zero-weight terms contribute zero to the identity. Both exact identities have maximum numerical discrepancy below $10^{-15}$. Values are on the zero-to-one loading scale, apart from the count row. They describe the frozen sample, without confidence intervals, a test of invariant state intensity or causal variance attribution.',['Quantity','Value or range','Denominator'],rows,[63,55,49]))
p=d['patient_permutation'];e=d['patient_equivalence']
rows=[['All label allocations',p['allocations']],['At least as extreme as observed',p['extreme_allocations']],
      ['Exhaustive two-sided probability',f(p['exact_probability'],6)],
      ['Recorded add-one probability',f(p['recorded_add_one_probability'],6)],
      ['Welch standard error',f(e['standard_error'],6)],['Welch degrees of freedom',f(e['welch_df'],6)],
      ['Two-sided 90% Welch interval',' to '.join(f(v,6) for v in e['two_sided_90_interval'])],
      ['Equivalence-margin infimum',f(e['equivalence_margin_infimum'],6)]]
p1.append(table('tab:p1exact',r'Independent arithmetic check of the all-cell mean-loading contrast in 11 patients (7 healing, 4 non-healing). Exhaustive allocation includes the observed labels and numerical ties: 89/330 allocations are at least as extreme in absolute mean difference, whereas the retained add-one convention gives 90/331. These probabilities assume observational label exchangeability and do not identify a causal effect. Welch quantities use sample variances within the two outcome groups. Standard error, interval and margin are on the loading scale; degrees of freedom and probabilities are dimensionless. A margin strictly greater than the infimum would be needed to reject both one-sided tests at 0.05. The data-derived boundary is not a clinical equivalence margin.',['Quantity','Value'],rows,[100,67]))
(HERE/'tables.tex').write_text('\n\n'.join(p1)+'\n')
